/* Generated by Babel */
'use strict';

(function () {
    var $ = document.querySelector.bind(document);
    var $$ = document.querySelectorAll.bind(document);

    var init = function init() {

        var tvTags = "";

        for (var i = 0; i < 18; i++) {
            for (var j = 19; j >= 0; j--) {
                tvTags += '<img id="' + i + '-' + j + '" src="img/200.gif" alt="">';
            }
        }
        //console.log("TV Tags" + tvTags);
        $('#site-wrapper').innerHTML = tvTags;
    };

    init();
})();